### ISSUE TITLE
WARNINGs and KeyError when `load_from_msp` MoNA LC-MS/MS Positive Mode MSP

### ISSUE THREAD

**Issue by kozo2** [matchms/matchms#551]
When I execute the code below,
```
# Get MoNA LC-MS/MS Positive Mode MSP zip file
wget https://mona.fiehnlab.ucdavis.edu/rest/downloads/retrieve/873fbe29-4808-46d1-a4a3-a4134ac8c755 
mv 873fbe29-4808-46d1-a4a3-a4134ac8c755 mona_msp.zip
unzip mona_msp.zip
```
```
from matchms.importing import load_from_msp

# Download msp file from MassBank of North America repository at https://mona.fiehnlab.ucdavis.edu/
file_msp = "MoNA-export-LC-MS-MS_Positive_Mode.msp"
tmp = load_from_msp(file_msp)
foo = list(tmp)
```

I get the following warnings and errors.
```
...
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-10-31 08:59:20,349:WARNING:matchms:add_retention:0.58-0.89 min can't be converted to float.
WARNING:matchms:0.58-0.89 min can't be converted to float.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-10-31 08:59:20,357:WARNING:matchms:add_retention:0.58-0.89 min can't be converted to float.
WARNING:matchms:0.58-0.89 min can't be converted to float.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-10-31 08:59:20,366:WARNING:matchms:add_retention:0.58-0.89 min can't be converted to float.
WARNING:matchms:0.58-0.89 min can't be converted to float.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-10-05474f543f9b>](https://localhost:8080/#) in <cell line: 1>()
----> 1 foo = list(tmp)

4 frames
[/usr/local/lib/python3.10/dist-packages/matchms/filtering/metadata_processing/add_retention.py](https://localhost:8080/#) in _safe_convert_to_float(value)
     63         if match and len(match.groups()) == 2:
     64             val, unit = value.split(' ')
---> 65             return float(val) * conversion[unit]
     66     try:
     67         value = float(value)

KeyError: 'sec'
```

If you have any ideas, please let me know.

The matchms version is `0.23.1` .
The Python version is `3.10.12`.

**Comment by niekdejonge** [comment]
Thanks for the clear issue and sorry for the delay in response, I missed it before. 
This is indeed an issue on the matchms side. I will implement a fix and hope to soon do a new release that addresses this issue.

**Comment by niekdejonge** [comment]
It took a bit longer than planned, but this should have been fixed with #553 and be available now in the new release of matchms 0.24.0. Let us know if this remains an issue. @kozo2

**Comment by kozo2** [comment]
Thank you @niekdejonge 

In version 0.24.0, that KeyError no longer occurs.

However, I still encountered an IndexError as shown below.

```
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-11-27 09:50:37,482:WARNING:matchms:add_precursor_mz:No precursor_mz found in metadata.
WARNING:matchms:No precursor_mz found in metadata.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-11-27 09:50:37,489:WARNING:matchms:add_precursor_mz:No precursor_mz found in metadata.
WARNING:matchms:No precursor_mz found in metadata.
WARNING:pickydict:Key 'exact_mass' will be interpreted as 'parent_mass'. But this entry already exists. Please use 'parent_mass' if you want to replace the entry.
2023-11-27 09:50:37,499:WARNING:matchms:add_precursor_mz:No precursor_mz found in metadata.
WARNING:matchms:No precursor_mz found in metadata.
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-4-5079fe4afd5e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 spectrums = list(tmp)

4 frames
[/usr/local/lib/python3.10/dist-packages/matchms/filtering/metadata_processing/interpret_pepmass.py](https://localhost:8080/#) in _get_mz_intensity_charge(pepmass)
     71             if len(matches) > 1:
     72                 raise ValueError("Found more than one tuple in pepmass field.")
---> 73             pepmass = matches[0].split(",")
     74         length = len(pepmass)
     75         values = [None, None, None]

IndexError: list index out of range
```

This can be reproduced with the following Google Colab notebook.

https://colab.research.google.com/drive/1wlBfQmOD6lw23NWeTvPQrq9fLT1DvjxQ?usp=sharing

Let me know if there is anything you have in mind.

**Comment by kozo2** [comment]
@niekdejonge Let me know if I should create a new issue for the `IndexError`.
https://github.com/matchms/matchms/issues/551#issuecomment-1827512235

**Comment by niekdejonge** [comment]
Ah sorry to hear that it still doesn't work, you seem unlucky with this dataformat... This seems unrelated to the previous issue. It is related to the code added in #539. I think I quickly implemented a fix in #583

Based on the code I would expect this will break for a pepmass of format "103.2", did you have a similar format? I will ask @hechth to review my fix, since he has a bit more experience with the different pepmass formats and implemented #539

**Comment by niekdejonge** [comment]
I created #584 to discuss this further
